repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe'] # checks syntax without loading yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: make-format
        name: autoformat
        entry: make format
        language: system
