[tool.black]
# Reference: https://github.com/psf/black
line-length = 100
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.isort]
# Reference: https://github.com/PyCQA/isort
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
default_section= "FIRSTPARTY"
sections= ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
no_lines_before = ["STDLIB", "LOCALFOLDER"]

[tool.pytest.ini_options]
# Reference: https://docs.pytest.org/
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
